site_name: NoFussFramework Community
pages:
- 'Community': index.md
theme_dir: '../mkdocs/themes/readthedocs'
site_dir: '../html/community'
repo_url: 'https://github.com/jarnix/nofuss'
google_analytics: ['UA-30907299-4', 'auto']
dev_addr: 0.0.0.0:81