site_name: NoFussFramework Documentation
pages:
    - [index.md, 'Documentation Home']
    - [intro/introduction.md, 'Introduction']
    - [setup/try-it-now.md, 'Try it now']
    - [setup/requirements.md, 'Getting started', 'Requirements']
    - [setup/installation.md, 'Getting started', 'Installation']
    - [configuration/introduction.md, 'Configuration', 'Introduction']
    - [configuration/config.ini.md, 'Configuration', 'config.ini']
    - [configuration/url.ini.md, 'Configuration', 'url.ini']
    - [configuration/routes.md, 'Configuration', 'routes']
theme_dir: '/var/www/nofussframework/mkdocs/themes/readthedocs-custom'
site_dir: '/var/www/nofussframework/html/docs'
repo_url: 'https://github.com/jarnix/nofuss'
google_analytics: ['UA-30907299-4', 'auto']
dev_addr: 0.0.0.0:81