site_name: NoFussFramework Documentation
pages:
- 'Documentation Home': index.md
- 'Introduction': intro/introduction.md
- 'Try it now': setup/try-it-now.md
- 'Getting started':
  - 'Requirements': setup/requirements.md
  - 'Installation': setup/installation.md
- 'Configuration': 
  - 'Introduction': configuration/introduction.md
  - 'config.ini - app settings': configuration/config.ini.md
  - 'config.ini - optional settings': configuration/config.ini-optional.md
  - 'url.ini': configuration/url.ini.md
  - 'routes': configuration/routes.md
- 'Reference':
  - 'sessions table structure': reference/sessions-table.md
theme_dir: '../mkdocs/themes/readthedocs'
site_dir: '../html/docs'
repo_url: 'https://github.com/jarnix/nofuss'
google_analytics: ['UA-30907299-4', 'auto']
dev_addr: 0.0.0.0:81
strict: true
