site_name: NoFussFramework Downloads
pages:
- 'Download': index.md
theme_dir: '../mkdocs/themes/readthedocs'
site_dir: '../html/download'
repo_url: 'https://github.com/jarnix/nofuss'
google_analytics: ['UA-30907299-4', 'auto']
dev_addr: 0.0.0.0:81
strict: true
